### ISSUE TITLE
Doesn't seem to work with the new ttf-joypixels package

### ISSUE THREAD

**Issue by linvain** [chrisdruta/arch-linux-apple-emojis#1]

**Comment by chrisdruta** [comment]
My computer recently died so now I'm on a macbook without any arch environment available.

Not sure what ttf-joypixelas has to do with the install instructions, but the install itself is quite simple / hacky. You just have to replace what ever emoji font file you have setup with the one from this repo and apple emojis should work.

**Comment by FranciscoDumont** [comment]
This worked for me:
`sudo cp Downloads/emojione.ttf /usr/share/fonts/TTF/JoyPixels.ttf`
